### ISSUE TITLE
a new exporter without a location returns an error about setting default location

### ISSUE THREAD

**Issue by odeke-em** [census-ecosystem/opencensus-go-exporter-stackdriver#164]
Given code that used to work in the past

```go
        projectID := "odeke-sandbox"
        sde, err := stackdriver.NewExporter(stackdriver.Options{
                ProjectID: projectID,
        })
        if err != nil {
                log.Fatalf("Failed to start Stackdriver OpenCensus exporter: %v", err)
        }
        defer sde.Flush()
        trace.RegisterExporter(sde)
```

I get back an unexpected error
```shell
$ GOOGLE_APPLICATION_CREDENTIALS=odeke-sandbox.json go run main.go 
2019/06/24 17:40:06 Setting Stackdriver default location failed: Get \
http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: \
i/o timeout
```

I believe we should only be trying to find a default location if we are on GCE and in the past we've been able to run this exporter on local computers or even on other clouds.

**Comment by DazWilkin** [comment]
I just noticed this too.

I am using the Agent to export to Stackdriver and, when I saw the error, reconfigured my client to use the Stackdriver exporter directly. Since the agent uses the same code, it's unsurprising that both fail.

Curiously, I do have some measurements recorded to Stackdriver so, somehow -- and I don't understand how -- I had this working albeit briefly.

**Comment by DazWilkin** [comment]
What's curious is that it's looking for `/instance/zone` in the metadata.

When I deployed the agent to a GCE VM, it *incorrectly* (because it's using this metadata link) binds to the VM's zone:
```
2019/06/26 16:47:06 Setting Stackdriver default location to "us-west1-c"
```
So, it's both ignoring my specified `project` value *and* it's choosing to reference `./instance/zone` when I assume it should be looking for:
```
curl \
--header "Metadata-Flavor: Google" \
http://169.254.169.254/computeMetadata/v1/project/project-id
```

**Comment by DazWilkin** [comment]
Hmmm:
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blame/master/stackdriver.go#L293

**Comment by odeke-em** [comment]
Kindly paging @fabxc @rghetia from https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/84

**Comment by rghetia** [comment]
It is misleading to print that message when it is not running on GCE. @odeke-em , @DazWilkin it should still continue to export the metrics/traces without location. Does it not?

Agent does not inject resource labels but it simply forwards those it receives from the client.

**Comment by DazWilkin** [comment]
I think so.

Confirming now.

I think this was a red-herring error for another issue that my client has.

**Comment by DazWilkin** [comment]
Yes, measurements are being reported by Stackdriver.
